name: Publish

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - 'v*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - run: yarn lint:test
      - run: yarn test
      - name: Version Bump
        id: versionbump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default: patch
          minor-wording: add,Adds,new
          major-wording: MAJOR,cut-major
          patch-wording: patch,fixes
          rc-wording: RELEASE,alpha
          commit-message: 'CI: bumps version to {{version}} [skip ci]'

  publish-npm:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: 12.x
          registry-url: https://registry.npmjs.org/
      - run: |
          npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          yarn npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
